Repository UKHomeOffice/hocs-management-ui, pull requests merged in 2022-03, with the labels that each got.

#175 HOCS-4696: use GitHub SemVer actions
  .drone.yml
  .github/workflows/label-check.yml
  .github/workflows/semver.yml
Labels: major

#177 Hocs-4696: Remove Sonar scan - should be done as another ticket
  .drone.yml
Labels: patch

#176 HOCS-4749: add linting/dry-run drone pipeline
  kube/.drone.yml
Labels: patch

#180 HOCS-4696: Override Dependabot labels
  .github/dependabot.yml
Labels: patch

#186 HOCS-4808: support tagging on support branches
  .drone.yml
Labels: patch

#189 Deploy the tag and not the commit sha
  .drone.yml
Labels: patch, skip-release
